language: r
cache: packages
latex: false
r_build_args:
r_check_args: --as-cran

# This is the minimal set of R packages needed to run "R CMD check" on
# the package.
install:
  - R -e 'install.packages(c("devtools","covr","testthat","dplyr","Rcpp","RcppArmadillo","RcppParallel","ggplot2","cowplot"))'
  - R -e 'devtools::install_github("linxihui/NNLM",upgrade = "never")'

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

after_success:
  - Rscript -e 'library(covr); codecov()'

branches:
  only:
    - master
